[pytest]
minversion = 7.0
# addopts = --cov=src
# addopts = -p no:warnings
addopts = --ignore=tests/test_model_AzureOpenAIChatReal.py --ignore=tests/test_application.py --ignore=tests/test_azure_auth_client.py
pythonpath = ./src
testpaths =
    tests
filterwarnings =
    ignore:.*jsonschema.RefResolver.*:DeprecationWarning
